### ISSUE TITLE
Building Advanced Contracts: upgrade a contract's class hash

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#592] opened 2024-02-13 01:35 UTC
- Explain how upgradeability works on starknet - class hash replacing vs proxy pattern
- Add an example using `replace_class_syscall`
- Maybe another example with OZ upgradeable component?

**Comment by talfao** [comment] 2024-02-18 20:36
I will take a look at this, if I may :)

**Comment by dubzn** [comment] 2024-02-20 10:12
gm sir, can i get this one? 
Do you think adding it to the [12. Starknet Smart Contracts](https://book.cairo-lang.org/ch99-00-starknet-smart-contracts.html) section would be appropriate?

**Comment by TAdev0** [comment] 2024-02-20 10:43
Hi @dubzn ,
Sure, this issue is available.
We are going to rework all the Smart Contracts section. But anyway, this will be a new .md file for this section, i think you can place it as 12.6.2. , in "Other Examples" subchapter? @enitrat  what do you think?

**Comment by enitrat** [comment] 2024-02-21 16:30
sure

**Comment by enitrat** [comment] 2024-03-20 22:02
#629

**Comment by OkoliEvans** [comment] 2024-03-21 02:27
If the issue is still open I'll love to take it. I once wrote an article about native upgradability of starknet contracts using `replace_class_syscall`... link to article here: https://medium.com/@mr.evans0075/native-upgradability-starknets-magic-syscall-for-upgrading-smart-contracts-314c2807b61e#:~:text=Native%20Upgradability%3A%20Starknet's%20Magic%20Syscall%20for%20Upgrading%20Smart%20Contracts,-Okoli%20Evans&text=Starknet%20is%20an%20Ethereum%20layer2,Rust%2Dinspired%20language%20called%20Cairo.

**Comment by dubzn** [comment] 2024-03-21 02:56
> If the issue is still open I'll love to take it. I once wrote an article about native upgradability of starknet contracts using `replace_class_syscall`... link to article here: https://medium.com/@mr.evans0075/native-upgradability-starknets-magic-syscall-for-upgrading-smart-contracts-314c2807b61e#:~:text=Native%20Upgradability%3A%20Starknet's%20Magic%20Syscall%20for%20Upgrading%20Smart%20Contracts,-Okoli%20Evans&text=Starknet%20is%20an%20Ethereum%20layer2,Rust%2Dinspired%20language%20called%20Cairo.

I was working on it but I couldn't give it the necessary continuity, if @enitrat sees it ok he can assign it to you, I will close my PR, you can check what I was writing if you like

**Comment by OkoliEvans** [comment] 2024-03-21 08:21
> > If the issue is still open I'll love to take it. I once wrote an article about native upgradability of starknet contracts using `replace_class_syscall`... link to article here: https://medium.com/@mr.evans0075/native-upgradability-starknets-magic-syscall-for-upgrading-smart-contracts-314c2807b61e#:~:text=Native%20Upgradability%3A%20Starknet's%20Magic%20Syscall%20for%20Upgrading%20Smart%20Contracts,-Okoli%20Evans&text=Starknet%20is%20an%20Ethereum%20layer2,Rust%2Dinspired%20language%20called%20Cairo.
> 
> I was working on it but I couldn't give it the necessary continuity, if @enitrat sees it ok he can assign it to you, I will close my PR, you can check what I was writing if you like

Alright, I will wait for the moderator to assign to me. Let me quickly go through what you have done so far

**Comment by enitrat** [comment] 2024-03-21 13:11
@dubzn has almost finished it, I will just add the comments from my review to his PR and close it

**Comment by dubzn** [comment] 2024-03-21 14:21
> @dubzn has almost finished it, I will just add the comments from my review to his PR and close it

Ok, lemme do it today sir!

**Comment by enitrat** [comment] 2024-03-21 14:39
@dubzn I did it in #706

**Closed** 2024-03-27 14:48 UTC
Labels: good first issue, Type: feature, Difficulty: intermediate
